#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    if id -u strfry >/dev/null 2>&1; then
        deluser --system strfry >/dev/null 2>&1 || true
    fi
    if getent group strfry >/dev/null 2>&1; then
        delgroup --system strfry >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#

exit 0
